# Start from the official Go base image
FROM golang:1.22-alpine as build

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go.mod and go.sum files to the workspace
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source code into the container
COPY . .

# Run the tests
CMD ["sh", "-c", "sleep 5 && go test -v ./... --cover"]